### ISSUE TITLE
Speed up swerve chassis code

### ISSUE THREAD

**Issue by auscompgeek** [thedropbears/pydeepspace#65]
A large portion of our control loop is spent in the chassis code. This is even reproducible in simulation on our laptops to the extent that we get Watchdog warnings!

I suspect most of the time is spent specifically in the least squares solver. We probably don't need to do that twice in the odometry.

**Comment by james-ward** [comment]
I think we can get rid of the speed related call. It only sets the `self.odometry_x_vel` etc members, which in turn are only used in the `chassis.speed` property which is never called anywhere else.

**Comment by james-ward** [comment]
Done!
